#! /bin/bash

set -e

# Default max workspaces = 1
gconftool-2 --direct \
    --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults \
    --type int \
        --set /apps/metacity/general/num_workspaces 1

# set the default background
gconftool-2 --direct \
    --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults \
    --type string \
    --set /desktop/gnome/background/picture_filename \
    /usr/share/backgrounds/camara-background-1.jpg

# set the default theme
gconftool-2 --direct \
    --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults \
    --type string \
    --set /desktop/gnome/interface/gtk_theme LiNsta3

# set the icon theme
gconftool-2 --direct \
    --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults \
    --type string \
    --set /desktop/gnome/interface/icon_theme OSX


chown -R camara.camara /home/camara/.themes/LiNsta3 
