
all: *.c
#	$(CC) -Os -static -DNCURSES_STATIC -lncurses -Wall *.c
#	$(CC) -Os -static -DNCURSES_STATIC -Wall *.c -L/usr/local/lib -lncurses
	$(CC) -Os -static -DNCURSES_STATIC -Wall *.c -lncurses

clean:
	rm -f a.out
	rm -f *.o

# eof
